# This workflow will upload Docker image when a release is created
# For more information see: https://github.com/marketplace/actions/docker-build-push-action

name: Publish docker image

on:
  workflow_dispatch:
  release:
    types:
    - published

jobs:
  publish:
    strategy:
      matrix:
        profile:
          - auto
          - comfy
    runs-on: ubuntu-latest
    name: ${{ matrix.profile }}
    steps:
      - uses: actions/checkout@v3
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: |
            p1c2u/stable-diffusion-webui-amdgpu-docker
          tags: |
            type=semver,pattern={{version}}-${{matrix.profile}}
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./services/${{matrix.profile}}/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
